"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# backend/project/settings.py
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# 基本設定
# =============================================================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 秘密鍵（本番では必ず環境変数で設定）
# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-!t4lbq4k8j5%xa6=4f(bea6fb*_)!3@dba5gpt05)s_rlpga4^'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-only-secret') # 開発では未設定でも動くようにデフォルトを用意

# デバッグ（本番では False）
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ホスト許可
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') # 開発では localhost と 127.0.0.1 を許可


# =============================================================================
# アプリケーション
# =============================================================================

# アプリケーション
# Application definition
INSTALLED_APPS = [
    # Django 標準アプリ
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # サードパーティ
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',  # JWTブラックリスト機能
    'django_filters',

    # 自作アプリ
    'api',
    'review',
    'game',
    'account',
]


# =============================================================================
# ミドルウェア
# =============================================================================

# ミドルウェア（CORSをSecurityの直後に移動）
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS ミドルウェアはできるだけ上に置く（Security の直後が推奨）
    'corsheaders.middleware.CorsMiddleware', # CORS ミドルウェアを追加

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================================================================
# CORS / CSRF 設定（React / Vite フロントエンドからのアクセス許可）
# =============================================================================

# フロントエンドのオリジンを許可
# Vite: 5173, CRA: 3000

# 開発用：React のポートを許可（Vite: 5173, CRA: 3000）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# セッション認証で Cookie を使うなら必要
CORS_ALLOW_CREDENTIALS = False

# CSRF の信頼オリジン（セッション認証で必要）
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# =============================================================================
# URL / WSGI
# =============================================================================

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# =============================================================================
# データベース
# =============================================================================

# データベース
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================================================================
# 認証 / ユーザーモデル
# =============================================================================

# カスタムユーザーモデル
# Custom User Model
AUTH_USER_MODEL = 'account.User'


# パスワード検証
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# 国際化
# =============================================================================

# 国際化
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# =============================================================================
# 静的ファイル / メディアファイル
# =============================================================================

# 静的ファイル
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# from pathlib import Path
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # collectstatic の出力先


# メディアファイル（画像など）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =============================================================================
# Django 共通設定
# =============================================================================

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# DRF / 認証設定
# =============================================================================

# REST Framework 基本設定
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # セッション認証を併用する場合は以下を追加
        # 'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # ← デフォルト値（※フロントから上書き可能）

    # 必要に応じて JSON 固定にする（ブラウザブラウザブルAPI不要なら）
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'rest_framework.renderers.JSONRenderer',
    # ],
}


# =============================================================================
# Simple JWT 設定
# =============================================================================

# JWTの詳細設定
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True, # リフレッシュ時に新しい refresh を発行
    'BLACKLIST_AFTER_ROTATION': True, # 古い refresh をブラックリスト入り
    'AUTH_HEADER_TYPES': ('Bearer',),
}