# Generated by Django 5.2.9 on 2025-12-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score']},
        ),
    ]
