# Generated by Django 5.2.9 on 2025-12-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cycling_road',
        ),
        migrations.DeleteModel(
            name='CyclingRoad',
        ),
    ]
